version: "3.4"
services:
    nginx-ssl:
        image: nginx
        container_name: nginx-ssl
        volumes:
            - type: bind
              source: $NGINX_DIR/nginx.conf
              target: /etc/nginx/nginx.conf
            - type: bind
              source: $NGINX_DIR/conf.d
              target: /etc/nginx/conf.d
        ports:
            - "$EXT_API_PORT:$API_PORT"
        depends_on:
            - es_api
    es:
        image: elasticsearch
        container_name: es
        volumes:
            - type: bind
              source: $ES_DATA_DIR
              target: /usr/share/elasticsearch/data
    es_api:
        build:
            context: .
        image: es_api:1.0
        container_name: es_api
        depends_on:
            - es
